// FRONT/REACT/dish-app/src/DishCreate/DishCreate.jsx
const DishCreate = (props) => {
    return(
        <div>
            <span>Nuevo plato</span>
            <br/>
            <label htmlFor="dishName">Nombre</label>
            <input type="text" id="dishName" />
            <br/>
            <label htmlFor="dishPrice">Precio</label>
            <input type="number" id="dishPrice"/>
            <br/>
            <button onClick={createDish}> Crear</button>
        </div>
    )

    function createDish()
    {
        console.log("createDish");
        let dishName = document.getElementById("dishName").value;
        console.log(dishName);
        
        let dishPrice = document.getElementById("dishPrice").value;
        console.log(dishPrice);

        console.log(props.dishes)

        let dish = {
        id: (props.dishes.length + 1).toString()
        , name: dishName
        , price: dishPrice
        }


        props.dishesChanger([...props.dishes, dish]);
    }


};

export default DishCreate;

// FRONT/VUE/dish-app/src/components/DishCreate.vue
<script>
export default
    {
        name: "DishCreate"
      , data() 
        {
            return  {mutDish: Object }
        }
      , methods: 
        {
            createDish
        }
      , emits: ["dishCreated"]
    }

    function createDish(event)
    {
        console.log("create Dish in CreateDsh")
        let nameDish = document.getElementById("dishName").value;
        console.log(nameDish)
        let priceDish = document.getElementById("dishPrice").value;
        console.log(priceDish)

        this.mutDish =
        {
            name: nameDish,
            price: priceDish
        }

        this.emits(event, {dish: this.mutDish})

    }
</script>

<template>
    <div>
        <span>Nuevo plato</span>
        <br>
        <label for="dishName">Nombre</label>
        <input type="text" id="dishName">
        <br>
        <label for="dishPrice">Precio</label>
        <input type="number" id="dishPrice">
        <br>
        <button v-on:click="createDish($event)"> Crear Plato</button>

    </div>

</template>

<style></style>
