// FRONT/REACT/dish-app/src/DishMenuItem/DishMenuItem.jsx
import { useState } from "react";

const DishMenuItem = (props) => {


    // function showMessage(event) 
    // {
    //     console.log("showMessage");
    //     console.log(event);
    //     console.log(event.target);
    //     console.log(event.target.innerText);
    
    //     document.getElementById("messageDiv").textContent 
    //     = event.target.innerText
    //     + " es barato ¡compra el plato! " + dish.name;
    // }
    
    // function onSale() 
    // {
    //     console.log("onSale")
    //     setDish(
    //         {
    //             ...dish
    //             ,  price: 5
    //         }
    //     )
    // }

    function removeDish()
    {
        console.log("removeDish id: " + props.dish.id);
        console.log(props.dishesChanger);

        let newDishes = [];

        props.dishes.forEach(dish => {
            if(dish.id != props.dish.id)
            { 
               newDishes = [...newDishes, dish] 
            }
        });

        props.dishesChanger(newDishes);

        }


    return(
        <>
            <img 
                src="chuleton-de-ternera.jpg"
                alt={props.dish.name}
                width="20%"
                />
            <h2>{props.dish.name}</h2>
            <h3>{props.dish.price}</h3>
            <button onClick={removeDish}>Borrar</button>
            <h4>{props.dish.price <= 30 ? "Ocasion": "Muy rico!"}</h4>
            {/* <h3 onMouseLeave={showMessage}>{props.dish.price}</h3>
            <div id="messageDiv"></div>
            <button onClick={onSale}>Poner en oferta</button> */}
        </>
    ) 
};

export default DishMenuItem;

// FRONT/VUE/dish-app/src/components/DishMenuItem.vue
<script>
export default
    {
        name: "DishMenuItem"
        , props: {
            dish: Object
        }
        // , data() 
        // {
        //     return  {
        //         dish: {
        //             name: "plato"
        //             , price: 20
        //         }
             
        //     }
        // } , methods:
        //     {
        //         showMessage, onSale
            // }
        
    };

    function showMessage(dish, event) 
    {
        console.log("ShowMessage");
        console.log(event);
        console.log(event.target);
        console.log(event.target.innerText)

        document.getElementById("messageDiv").textContent 
        = event.target.innerText
        + " es barato. compra el plato " + dish.name;
    };
    function onSale()
    {
        console.log("OnSale")

        this.dish.price = 5;

    }

</script>

<template>
    <img 
        src="../assets/chuleton-de-ternera.jpg" 
        v-bind:alt="dish.name"
        width="250em"></img>
    <h2>{{ dish.name }}</h2>
    <h3>{{ dish.price }}</h3>
    <h4 v-if="dish.price <=30">¡Ocasion!</h4>
    <h4 v-else>Muy rico</h4>
    <!-- <h3 v-on:mouseleave="showMessage(dish, $event)">{{ dish.price }}</h3> -->
    <!-- <div id="messageDiv"></div>
    <button v-on:click="onSale()">Poner en Oferta</button> -->
</template>

<style></style>
