// FRONT/REACT/dish-app/src/DIshDM/DishDM.jsx
import { useEffect } from "react";

const DishDM = (props) => {

    useEffect(
        () => {
            console.log("Effect en DM");

            props.dishesChanger(
                [
                    {
                        id: "1"
                        , name: "plato1"
                        , price: 20
                    }, {
                        id: "2"
                        , name: "plato2"
                        , price: 30
                    }, {
                        id: "3"
                        , name: "plato3"
                        , price: 40
                    }
                ]
        
            );

        }, []
    )


    return(
        <h2></h2>
    ) 
};

export default DishDM;

// FRONT/VUE/dish-app/src/components/DishDM.vue
<script>
export default {
      name: "DishDM"
    , props:  {
        dishes: {  
            type: Array
            , default: 
                [
                    {
                        name: "plato1"
                        , price: 20
                    }
                    , {
                        name: "plato2"
                        , price: 30
                    }
                    , {
                        name: "plato3"
                        , price: 40
                    }
                ]
        }

    }
    , emits: [
        "dishesUpdated"
    ]
    , created() {
        console.log("Created en DishDM");
        console.log(this.dishes);

        this.$emit("dishesUpdated", {dishes: this.dishes})
    }

}
</script>

<template>
</template>

<style></style>
